spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  redis:    host: localhost
    port: 6379
  session: 
    timeout: 600
    store-type: redis
    redis: 
      flush-mode: on-save      namespace: spring:session
  mail:
    host: smtp.gmail.com
    port: 587
    username: blog.dannys@gmail.com
    password: ehddus5603!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:\temp
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://49.50.164.225:3306/DVR?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.sbs.dan.at.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
custom:
  siteName: 데빌런
  siteMainUri: https://service.n32.st.dailyvillains.site
  logoText: 데빌런
  emailFrom: blog.dannys@gmail.com
  emailFromName: 데빌런

---

spring:
  profiles: local
server:
  port: 8088

---

spring:
  profiles: production
  servlet:
    multipart:
      location: /tmp
  datasource:
    username: dvl
    password: DANNYkim5603!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.50.164.225:3306/st_n32_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull